# Generated by Django 6.0.5 on 2026-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('google', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='road',
        ),
    ]
