# Generated by Django 6.0.5 on 2026-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_login_delete_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('google', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image')),
                ('Level', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior')], default='level', max_length=50)),
                ('category', models.CharField(choices=[('Language', 'Language'), ('programming', 'programming'), ('cyber_security', 'cyber_security'), ('graphic_design', 'graphic_design'), ('Marketing', 'Marketing'), ('Writing', 'Writing'), ('Ai', 'Ai')], default='Skills', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
