# Generated by Django 6.0.5 on 2026-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='google',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='name@gmail.com', max_length=254, unique=True),
        ),
    ]
