# Generated by Django 6.0.5 on 2026-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_user_email_remove_user_image_remove_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
