# Generated by Django 6.0.5 on 2026-06-29 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='المجتمع')),
            ],
            options={
                'verbose_name': 'المجتمع',
                'verbose_name_plural': 'المجتمعات',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_forum', models.CharField(max_length=150, verbose_name='أسم المنتدي')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forum_community', to='mpook.community', verbose_name='المجتمع التابع له')),
            ],
            options={
                'verbose_name': 'منتدي',
                'verbose_name_plural': 'المنتديات',
                'ordering': ['community', 'name_forum'],
                'unique_together': {('community', 'name_forum')},
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مسار التعلم')),
                ('description', models.TextField(verbose_name='وصف المسار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_path', to='mpook.community', verbose_name='المجتمع التابع له')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_path', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المسار')),
            ],
            options={
                'verbose_name': 'مسار التعلم',
                'verbose_name_plural': 'مسارات التعلم',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75, verbose_name='عنوان')),
                ('query', models.TextField(verbose_name='ألسؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_post', to=settings.AUTH_USER_MODEL, verbose_name='كاتب')),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ألاجابة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_answer', models.URLField(verbose_name='رابط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_answers', to=settings.AUTH_USER_MODEL, verbose_name='كاتب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_post', to='mpook.post')),
            ],
            options={
                'verbose_name': 'اجابة',
                'verbose_name_plural': 'الأجابات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Junior', 'مبتديء'), ('Senior', 'محترف')], max_length=100, verbose_name='المستوي')),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='معرض ألاعمال')),
                ('bio_headline', models.CharField(blank=True, max_length=200, null=True, verbose_name='وصف لي أهم أنجازاتك')),
                ('joined_formus', models.ManyToManyField(blank=True, related_name='members', to='mpook.forum', verbose_name='المنتديات المنضم اليها')),
                ('primary_forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialist_profile', to='mpook.forum', verbose_name='التخصص')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف الشخصي',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_post', to='mpook.profile'),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='عنوان البحث')),
                ('abstract', models.TextField(verbose_name='البحث بالكامل')),
                ('seeker_note', models.CharField(blank=True, max_length=300, null=True, verbose_name='ملاحظة الباحث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='نشرت')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_community', to='mpook.community', verbose_name='بحوث المجتمع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeker_user', to=settings.AUTH_USER_MODEL, verbose_name='باحث')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='المؤيدون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_review', to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_search', to='mpook.search')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'مراجعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتيب الخطوة')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='path_steps', to='mpook.learningpath', verbose_name='المسار')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpook.search', verbose_name='البحث المرتبط بهذه الخطوة')),
            ],
            options={
                'verbose_name': 'خطوة في المسار',
                'verbose_name_plural': 'خطوات المسار',
                'ordering': ['order'],
                'unique_together': {('path', 'order')},
            },
        ),
    ]
