# Generated by Django 6.0.5 on 2026-06-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_formus',
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_forums',
            field=models.ManyToManyField(blank=True, related_name='joined_forums', to='mpook.forum', verbose_name='المنتديات المنضم اليها'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_answer', to='mpook.post'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answer', to=settings.AUTH_USER_MODEL, verbose_name='كاتب'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_learningpath', to='mpook.community', verbose_name='المجتمع التابع له'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_learningpath', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المسار'),
        ),
        migrations.AlterField(
            model_name='pathstep',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learningpath_pathstep', to='mpook.learningpath', verbose_name='المسار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_post', to=settings.AUTH_USER_MODEL, verbose_name='كاتب'),
        ),
        migrations.AlterField(
            model_name='review',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_review', to='mpook.search'),
        ),
        migrations.AlterField(
            model_name='search',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_search', to='mpook.community', verbose_name='بحوث المجتمع'),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_search', to=settings.AUTH_USER_MODEL, verbose_name='باحث'),
        ),
    ]
